[workspace] 
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
matsengrp_rich_example = { path = "." }
hatch = ">=1.14.0,<2"

[tasks] 
start = "rich-example-main"

[package]  # this could also be ... features.default ?
name = "matsengrp_rich_example"
version = "0.1.3"

[package.build] 
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies] 
rich = "13.9.*"
