[project]
dependencies = ["rich"]                               
name = "matsengrp_rich_example"
requires-python = ">= 3.11"
scripts = { rich-example-main = "matsengrp_rich_example:main" } 
version = "0.1.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"