name: Build and Publish Python Package with Pixi

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: setup pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.42.1
        cache: true
  
    - name: Install dependencies with Pixi
      run: |
        pixi install
  
    - name: Build package with Hatchling
      run: |
        pixi run hatch build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
      
